### ISSUE TITLE
Atom feed not working

### ISSUE THREAD

**Issue by mktakuya** [wassan128/blog#1]
I want to read your blog on RSS Reader.

![atom](https://cloud.githubusercontent.com/assets/2035364/9809627/f3a3b7f4-58a4-11e5-9c7a-01768c22b7cd.gif)

**Comment by wassan128** [comment]
Now you can read atom.xml.
Thank you for pointing it out.

**Comment by mktakuya** [comment]
Nice work :+1:
Thank you!
